name: django-backend

services:
  django:
    image: tixidest/django:v1
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./secrets.json:/run/secrets/secrets.json
    labels:
      - "service=django"
    expose:
      - "8000"
   